### PR TITLE
Dark light themes

### PR DESCRIPTION
**Pull request by alia-stith**
Created 2 color files (default & dark) - theme file automatically selects which to use. Temp signup/login activity page shows use of theme colors using ?attr/[name] from the theme file.

### CODE REVIEW

**Review by Mozmani — CHANGES_REQUESTED** [review]
Change the colors file names, it's confusing!

**Comment by alia-stith** [comment]
> 

No, they're supposed to have the same name with different annotations so that you know what they're used for and when they're used. :)

**Comment by Mozmani** [comment]
> > 
> 
> No, they're supposed to have the same name with different annotations so that you know what they're used for and when they're used. :)

ohh okay!

**Review by Mozmani — APPROVED** [review]
Looks good to me, you are an amazing programmer!

**Pull request merged**
